name: .NET CI/CD

on:
  push:
    branches:
      - develop
      - main
      - "feature/*"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Gastos.API
        run: dotnet build --no-restore --configuration Release Gastos.API/Gastos.API.csproj

      - name: Build Gastos.MVC
        run: dotnet build --no-restore --configuration Release Gastos.MVC/Gastos.MVC.csproj

      - name: Build Gastos.Data
        run: dotnet build --no-restore --configuration Release Gastos.Data/Gastos.Data.csproj

      - name: Test Gastos.API
        run: dotnet test --no-build --verbosity normal Gastos.API/Gastos.API.csproj

      - name: Test Gastos.MVC
        run: dotnet test --no-build --verbosity normal Gastos.MVC/Gastos.MVC.csproj

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PowerShell Toolkit
        uses: hugoalh-studio/setup-powershell-toolkit-ghaction@v2.0.0

      - name: List output directories
        run: |
          echo "Listing files in the output directories:"
          ls -alh ${GITHUB_WORKSPACE}/Gastos.API/bin/Release/net8.0/
          ls -alh ${GITHUB_WORKSPACE}/Gastos.MVC/bin/Release/net8.0/
          ls -alh ${GITHUB_WORKSPACE}/Gastos.Data/bin/Release/net8.0/

      - name: Run FTP deployment script (simulated)
        run: |
          echo "Simulating FTP deployment script for Gastos.API"
          pwsh -Command "& '${{ github.workspace }}/.github/scripts/deploy.ps1' -ftpServer '${{ secrets.FTP_SERVER }}' -ftpUsername '${{ secrets.FTP_USERNAME }}' -ftpPassword '${{ secrets.FTP_PASSWORD }}' -localPath '${{ github.workspace }}/Gastos.API/bin/Release/net8.0/' -remotePath 'www.gastosapp.com/GastosAPI'"
          
          echo "Simulating FTP deployment script for Gastos.MVC"
          pwsh -Command "& '${{ github.workspace }}/.github/scripts/deploy.ps1' -ftpServer '${{ secrets.FTP_SERVER }}' -ftpUsername '${{ secrets.FTP_USERNAME }}' -ftpPassword '${{ secrets.FTP_PASSWORD }}' -localPath '${{ github.workspace }}/Gastos.MVC/bin/Release/net8.0/' -remotePath 'www.gastosapp.com/GastosMVC'"

          echo "Simulating FTP deployment script for Gastos.Data"
          pwsh -Command "& '${{ github.workspace }}/.github/scripts/deploy.ps1' -ftpServer '${{ secrets.FTP_SERVER }}' -ftpUsername '${{ secrets.FTP_USERNAME }}' -ftpPassword '${{ secrets.FTP_PASSWORD }}' -localPath '${{ github.workspace }}/Gastos.Data/bin/Release/net8.0/' -remotePath 'www.gastosapp.com/GastosData'"
          
        env:
          FTP_SERVER: "ftp.gastosapp.com"
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
